server:
  port: 9000

spring:
  application:
    name: center # 服务名称
# 服务注册中心配置
eureka:
  server:
    #自我保护机制（安全模式）
    enable-self-preservation: false
    #启用主动失效，并且每次主动失效检测间隔为3s
    eviction-interval-timer-in-ms: 4000
  instance:
    prefer-ip-address: true
    #服务刷新时间配置，每隔这个时间会主动心跳一次，默认30s
    lease-renewal-interval-in-seconds: 50
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    # 注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    # 默认90s
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: false
    #设置默认请求地址，Eureka给定默认值为8761
    service-url:
      defaultZone: http://localhost:9000/