server:
  port: 9003

spring:
  application:
    name: client
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
logging:
  level:
    org.springframework.cloud: info
    org.springframework.boot: info