spring:
  application:
    name: config-client
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
logging:
  level:
    org.springframework.cloud: info
    org.springframework.boot: info
  #配合消息总线使用
#  rabbitmq:
#    host: localhost
#    port: 7672
#    username: guest
#    password: guest
