logging:
  level:
    org.springframework.cloud: info
    org.springframework.boot: info
  #配合消息总线使用
#  rabbitmq:
#    host: localhost
#    port: 7672
#    username: guest
#    password: guest
version:
  1234567890
